/* EED HALAL — Menu database for budget calculator — auto-export 9/10/2569 07:19:59 */
var EED_DEFAULT_TOPPINGS = [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}];
var EED_MENUS = [
  { id: 20, name: "ข้าวหมกน่องไก่", price: 85, tier: "classic", image: "img/Chicken_Biryani_with_Chicken_Drumstick.jpg", desc: "ข้าวหมกน่องไก่ชิ้นใหญ่", badge: "⭐ Best Seller", minPerMenu: 10, sortOrder: 1, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 6, name: "ข้าวไก่กระเทียม", price: 65, tier: "classic", image: "img/chicken-garlic-omelette.jpg", desc: "ไก่ทอดกระเทียมกรอบหอม + ข้าวสวย", badge: "", minPerMenu: 10, sortOrder: 2, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 14, name: "ข้าวไก่เทอริยากิ", price: 85, tier: "classic", image: "img/chicken-teriyaki.jpg", desc: "เนื้อไก่นุ่มๆ ชิ้นโต ย่างจนหอมกรุ่น ราดด้วยซอสเทอริยากิสูตรเข้มข้น รสชาติหวานเค็มกลมกล่อมสไตล์ญี่ปุ่นแท้ๆ", badge: "", minPerMenu: 10, sortOrder: 3, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 8, name: "ข้าวผัดเนื้อเค็มพริกขี้หนู", price: 80, tier: "classic", image: "img/salted-beef-chili-fried-rice.jpg", desc: "เนื้อเค็มหั่นเต๋าผัดข้าวหอมกระเทียมเจียว", badge: "", minPerMenu: 10, sortOrder: 4, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 17, name: "ข้าวคั่วกลิ้งไก่สับ", price: 65, tier: "classic", image: "img/kua-kling-chicken.jpg", desc: "ไก่สับคั่วแห้งๆ เคล้าพริกแกงใต้สูตรเข้มข้น รสชาติเผ็ดร้อน จัดจ้านถึงใจ หอมกลิ่นตะไคร้และใบมะกรูดซอยอย่างแรง", badge: "best seller", minPerMenu: 10, sortOrder: 5, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 3, name: "ผัดไทยกุ้งสด", price: 90, tier: "classic", image: "img/pad-thai-shrimp.jpg", desc: "เส้นนุ่มรสกลมกล่อม กุ้งสดตัวโต", badge: "", minPerMenu: 10, sortOrder: 6, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 29, name: "ข้าวผัดกะเพราเนื้อ", price: 80, tier: "classic", image: "img/menu-kaprao-nuea.jpg", desc: "เพิ่มผลไม้สดตามฤดูกาล", badge: "+ ผลไม้", minPerMenu: 10, sortOrder: 7, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 16, name: "ข้าวหมกไก่สะโพก", price: 110, tier: "classic", image: "img/menu-khao-mok.jpg", desc: "ข้าวหมกหอมเครื่องเทศ เสิร์ฟพร้อมไก่นุ่ม", badge: "⭐ Best Seller", minPerMenu: 10, sortOrder: 8, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 24, name: "ข้าวเหลืองไก่ทอดเครื่อง", price: 90, tier: "classic", image: "img/spiced-fried-chicken.jpg", desc: "ไก่ทอดเครื่องหอมสมุนไพร + ข้าวเหลือง", badge: "พรีเมียม", minPerMenu: 10, sortOrder: 9, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 117, name: "ข้าวผัดปู", price: 140, tier: "classic", image: "img/Crab_Fried_Rice.jpg", desc: "ข้าวร่วนนุ่มหอมกลิ่นกระทะ อัดแน่นด้วยเนื้อปูก้อนหวานฉ่ำเต็มคำ อร่อยฟินจนหยุดกินไม่ได้!", badge: "ใหม่", minPerMenu: 10, sortOrder: 10, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 119, name: "ข้าวผัดทะเล", price: 105, tier: "classic", image: "img/Seafood_Fried_Rice.jpg", desc: "เซตอาหารสุดลงตัวที่ได้ทั้งโปรตีนเข้มข้นจากซีฟู้ดผัดร้อนๆ (กุ้ง ปลาหมึก) และความสดชื่นล้างปากจากผลไม้", badge: "ใหม่", minPerMenu: 10, sortOrder: 12, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 114, name: "เซ็ตพรีเมียม ข้าวผัดกะเพราเนื้อ ไข่ดาว + แกงจืด + ผลไม้สด", price: 230, tier: "executive", image: "img/premium-set.jpg", desc: "เซ็ตพรีเมียม ข้าวผัดกะเพราเนื้อวัว ไข่ดาว + แกงจืดเต้าหู้ไก่สับ + ผลไม้สด", badge: "ใหม่", minPerMenu: 10, sortOrder: 43, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 115, name: "ข้าวไก่ทอด แกงเผ็ดเป็ดย่าง ผลไม้", price: 180, tier: "signature", image: "img/signature-red-curry-opt.jpg", desc: "ข้าวไก่ทอดกรอบๆ คู่แกงเผ็ดเป็ดย่างรสเข้มข้นเปรี้ยวหวาน ตบท้ายด้วยผลไม้สดแช่เย็นล้างปาก อร่อยครบรสในมื้อเดียว", badge: "ใหม่", minPerMenu: 10, sortOrder: 44, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 116, name: "ข้าวผัดปลาอินทรีทอดเครื่องเทศ ซุปอิสลามไก่", price: 160, tier: "signature", image: "img/signature-fried-rice-opt.jpg", desc: "ข้าวผัดปลาอินทรีทอดเครื่องเทศ หอมสมุนไพรเข้มข้น ทานคู่กับ ซุปอิสลามไก่ รสแซ่บจัดจ้าน เปรี้ยวเผ็ดร้อน หอมหอมเจียว ซดคล่องคออร่อยลงตัว", badge: "ใหม่", minPerMenu: 10, sortOrder: 45, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 120, name: "กะเพราไก่ราดข้าว", price: 65, tier: "classic", image: "img/Ckrapow-gai-kai-dow-fruit.jpg", desc: "กะเพราไก่ร้อนๆ ราดข้าวสวยหอมนุ่ม ไข่ดาวกรอบเยิ้ม ตบท้ายด้วยผลไม้สดชื่นเต็มคำ!", badge: "ใหม่", minPerMenu: 10, sortOrder: 46, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 121, name: "กะเพราเนื้อราดข้าว", price: 80, tier: "classic", image: "img/krapow-neua-kai-dow-fruit.jpg", desc: "กะเพราเนื้อหอมกรุ่น เนื้อนุ่มชุ่มซอส ราดบนข้าวสวยร้อนๆ ไข่ดาวเยิ้มพร้อมเจิรญ ผลไม้สดเพิ่มความสดชื่น!", badge: "ใหม่", minPerMenu: 10, sortOrder: 47, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 122, name: "ข้าวไก่ทอด แกงกะหรี่ปลาอินทรี และซาโมซา", price: 220, tier: "signature", image: "img/fried-chicken-curry-fish-samosa.jpg", desc: "ข้าวร้อนๆ กับไก่ทอดกรอบนอกนุ่มใน แกงกะหรี่ปลาอินทรีหอมเผ็ดร้อน ซาโมซากรอบๆ ตบท้าย อร่อยจัดเต็มสไตล์อินเดีย!", badge: "ใหม่", minPerMenu: 10, sortOrder: 48, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 123, name: "ผัดพริกแกงกุ้ง", price: 90, tier: "classic", image: "img/phad-prik-gaeng-goong-kai-jeaw.jpg", desc: "ผัดพริกแกงกุ้งหอมเผ็ดกลิ่นเครื่องเทศเข้มข้น กุ้งเด้งสด ไข่เจียวฟูนุ่มชุ่มน้ำ ซดกับข้าวสวยร้อนๆ", badge: "ใหม่", minPerMenu: 10, sortOrder: 49, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 124, name: "ปลาหมึกทอดกระเทียม", price: 105, tier: "classic", image: "img/fried-squid-garlic-omelette.jpg", desc: "ปลาหมึกทอดกรอบนอกนุ่มใน หอมกระเทียมโขลก แซ่บจนน้ำลายสอ! ไข่เจียวฟูนุ่มทานคู่กัน", badge: "ใหม่", minPerMenu: 10, sortOrder: 50, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 125, name: "ผัดผักรวมมังสวิรัติ", price: 65, tier: "classic", image: "img/mixed-vegetable-stirfry-vegetarian.jpg", desc: "ผัดผักรวมสดๆ หลากสี หอมกระเทียมพริกไทย ปรุงรสกลมกล่อมแบบมังสวิรัติ ทานกับข้าวสวยร้อนๆ", badge: "ใหม่", minPerMenu: 10, sortOrder: 51, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 126, name: "แกงเขียวหวานเนื้อ", price: 90, tier: "classic", image: "img/green-curry-beef-omelette.jpg", desc: "แกงเขียวหวานเนื้อนุ่มชุ่มซอส หอมเครื่องแกง กะทิกลมกล่อม ไข่เจียวฟูนุ่มชุ่มน้ำ ตักทานกับข้าวสวยร้อนๆ", badge: "ใหม่", minPerMenu: 10, sortOrder: 52, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 127, name: "ข้าวผัดต้มยำทะเล ไข่ต้ม", price: 115, tier: "classic", image: "img/tom-yum-seafood-fried-rice-boiled-egg.jpg", desc: "ข้าวผัดซึมซาบรสต้มยำทะเล หอมใบมะกรูด ตะไคร้ พริก ข้าวสวยร้อนๆ ไข่ต้มนุ่มๆ เพิ่มความเข้มข้น", badge: "ใหม่", minPerMenu: 10, sortOrder: 53, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 128, name: "ข้าวแกงเขียวหวานไก่ ไข่ดาว", price: 75, tier: "classic", image: "img/green-curry-chicken-rice-sunny-side-up.jpg", desc: "แกงเขียวหวานไก่หอมเครื่องแกง กะทิเข้มข้น ไก่นุ่มชุ่มซอส ราดข้าวสวยร้อนๆ", badge: "ใหม่", minPerMenu: 10, sortOrder: 54, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 129, name: "ข้าวปลาทอดกะเทียม", price: 105, tier: "classic", image: "img/fried-fish-garlic-rice.jpg", desc: "ปลาทอดกรอบนอกนุ่มใน โรยกระเทียมโขลกหอมกรุ่น เสิร์ฟพร้อมข้าวสวยร้อนๆ", badge: "ใหม่", minPerMenu: 10, sortOrder: 55, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] },
  { id: 130, name: "ผัดไทยกุ้งสดห่อไข่", price: 115, tier: "classic", image: "img/pad-thai-egg-wrap.jpg", desc: "ผัดไทยเส้นเหนียวนุ่ม กุ้งสดเด้ง ห่อไข่บางๆ กรอบนอกนุ่มใน รสเปรี้ยวหวานเค็มกลมกล่อม ตบท้ายถั่วงอกและผักสด", badge: "ใหม่", minPerMenu: 10, sortOrder: 56, toppings: [{"name":"ไข่ดาว","price":10},{"name":"ไข่เจียว","price":10},{"name":"ไข่ต้ม","price":10},{"name":"ผลไม้","price":35},{"name":"ซาโมซ่าไก่","price":10},{"name":"ซาโมซ่าเนื้อ","price":15}] }
];
